name: バグ報告
title: "【バグ】 "
description: "バグを発見/報告する場合はこちら"
labels: 🐛バグ
#assignees: " "

body:
- type: markdown
  attributes:
    value: |
      ## 下記を記入してください
- type: textarea
  id: feature
  attributes:
    label: 内容
    description: バグの詳細な内容を記載してください。発生条件が判明している場合は発生条件も記載してください。